apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yeb0k9ekn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:69e74c63e5ede16a55f39b6d203572e42fcbbf45@sha256:dd8c79c45fbd30996407e635738b3a035ec80e25590eba19afbcd3859c199e6c
          name: container-image
