apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yeb0k9ekn-nodejs
  janus-idp.io/tekton: yeb0k9ekn-nodejs
  backstage.io/kubernetes-id: yeb0k9ekn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yeb0k9ekn-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
