apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yeb0k9ekn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yeb0k9ekn-nodejs 
  name: yeb0k9ekn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yeb0k9ekn-nodejs 
